version: "3.9"
services:
  app:
    build:
      context: ./
    volumes:
      - ./:/usr/src/Powerflex-Sprocket-API
      - /usr/src/Powerflex-Sprocket-API/venv
    restart: unless-stopped
    env_file:
      - .env

networks:
  default:
    name: 'powerflex-sprocket-api'